### ISSUE TITLE
check run fails

### ISSUE THREAD

**Issue by teadur** [logan2211/ansible-bird#10]
if you want to check the difference of bird config generated with -DC flags on ansible-playbook run, the run fails with: 
TASK [bird : Set the name of pid1] *********************************************
fatal: [xxxx]: FAILED! => {"failed": true, "msg": "the field 'args' has an invalid value, which appears to include a variable that is undefined. The error was: 'dict object' has no attribute 'stdout'\n\nThe error appears to have been in 'xxxxx/roles/bird/tasks/main.yml': line 24, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Set the name of pid1\n  ^ here\n"}

**Comment by logan2211** [comment]
#11 will fix this however it breaks ansible 1.9 and 2.1 compatibility. I think this will be OK for the next tag however I am considering doing a branch to carry 1.9/2.1 compatibility for a while.

**Comment by logan2211** [comment]
@teadur: Could you try #11 with check mode now and let me know if that fixes the problem? I think it is fixed and maintains ansible 1.9/2.1/2.2 compatibility.

**Comment by teadur** [comment]
Works fine for me, thank you :)
Tested on: ansible 2.1.1.0
